### ISSUE TITLE
Real debian or not ?

### ISSUE THREAD

**Issue by zeroheure** [scottwilliambeasley/debian-from-scratch#2]
The paragraph about sources.list make it clear that we will build a real Debian system (even if it is not vanilla). But the intro and the conclusion are a little ambiguous : is it an apt based system with its own repositories, a Debian-like system or a real Debian (but not vanilla) ?

**Comment by android-808** [comment]
From what I can make out from skimming over the text, what you are essentially doing (heavily simplified) is:
Installing dpkg manually
Installing apt (+depends) from Debian
Installing other essential debs from Debian (inc. replacing your custom dpkg) to end up with a base image.

If I'm right, you are using the LFS /tools and some manual intervention in place of the Debian Installer to manually create a base image.

To create a custom apt-based system would be a lot more work as you would want to create custom packages (Debian folder, control file, rules, pre/post-inst) for each package during Chapter 6. IIRC you then install the packages with dpkg --root if dpkg is installed in /tools as part of the toolchain in Chapter 5.

**Comment by scottwilliambeasley** [comment]
You fellows are correct - what's outlined in the description versus the actual procedure outlined here are different. Thank you for pointing this out.

This manual indeed only creates a base image instead of manually creating custom packages for each individual part of the Debian system. 

The project description has been updated to clarify this and also commit 2736708 has been pushed to fix this in README.md.
