### ISSUE TITLE
Merge request?

### ISSUE THREAD

**Issue by tcreek** [scottwilliambeasley/debian-from-scratch#6]
So, after some tinkering, I was able to get dpkg compiled and installed without issue.

I see in the other thread you mention about a merge request.

What did you want to merge it with?

**Comment by scottwilliambeasley** [comment]
Sorry - I use Gitlab at work, and seldom use Github, which is why the terminology may be confusing. The Gitlab terminology 'merge request' is equivalent to the Github term 'pull request'.

Basically, the scenario here is that you've found something that you want to fix/improve on, and have the code for doing so.

In the case of this project, it mainly consists of Github flavored markdown (if you examine the raw source of README.MD) which gets rendered automatically into HTML by the Github site.

So, your code (a modification of README.MD) would change the guide to update/improve it by creating new/clarifying existing instructions, in the same style as the original. 

Since you've found something you want to change, you should 
1.) create a fork of the repo, 
2.) change the README.MD of your repo to reflect the fixed/improved contents, 
3.) submit a pull request. 

Inside of the pull request body, reference the original issue number, what the proposed change fixes/improves etc. Basically, describe what the problem was, how it is fixed etc.

Once you create the pull request, project owners/maintainers can approve your change to merge the changes back into the main branch of the project.

The following link should help you to get the basic gist of it:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by tcreek** [comment]
Thanks for the detailed information. 

I have installed "GitKraken" which has a free license for Open Source projects.

I will need to figure out how that that works.

**Comment by scottwilliambeasley** [comment]
I'm happy to point the way for other contributors for the project. 

You don't really need to use other software though - for the scope of this project the Github GUI should be enough to fork, make the changes to your fork, and submit a merge request upstream.

I suggest starting with a small, specific change followed by a merge request - in other open source projects, you are very likely to get your pull requests denied if the scope of what you're trying to change is too large. This is a best practice and should help you get used to the flow of committing, submitting pulls and working with maintainers to get your code pulled upstream.

As I've given you the basic flow/idea of contributing using merge requests, I will now be closing out this specific issue. Feel free to reach out if you have other issues.
